# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'ParseBandApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'Mixpanel'
    pod 'TwitterKit'
    pod 'Fabric'
    pod 'TwitterCore'
    pod 'Mixpanel-swift'
    source 'https://github.com/CocoaPods/Specs.git'
    #platform :ios, '7.0'
    pod 'AFNetworking', '~> 2.5'
    

  # Pods for ParseBandApp

end
